In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'
page = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
soup = BeautifulSoup(page.text, 'html')

## HTML tags

In [4]:
# soup.<tag>: Return content between opening and closing tag including tag

soup.title

In [5]:
# soup.<tag>.string: Return string within given tag

soup.title.string

'List of largest companies in the United States by revenue - Wikipedia'

In [6]:
# Find all the links within page’s <a> tags

soup.a

In [7]:
all_a = soup.find_all('a')
print('Total number of URLs:',len(all_a)) 
all_a

Total number of URLs: 373

[<a class="mw-jump-link" href="#bodyContent">Jump to content</a>,
 <a accesskey="z" href="/wiki/Main_Page" title="Visit the main page [z]"><span>Main page</span></a>,
 <a href="/wiki/Wikipedia:Contents" title="Guides to browsing Wikipedia"><span>Contents</span></a>,
 <a href="/wiki/Portal:Current_events" title="Articles related to current events"><span>Current events</span></a>,
 <a accesskey="x" href="/wiki/Special:Random" title="Visit a randomly selected article [x]"><span>Random article</span></a>,
 <a href="/wiki/Wikipedia:About" title="Learn about Wikipedia and how it works"><span>About Wikipedia</span></a>,
 <a href="//en.wikipedia.org/wiki/Wikipedia:Contact_us" title="How to contact Wikipedia"><span>Contact us</span></a>,
 <a href="/wiki/Help:Contents" title="Guidance on how to use and edit Wikipedia"><span>Help</span></a>,
 <a href="/wiki/Help:Introduction" title="Learn how to edit Wikipedia"><span>Learn to edit</span></a>,
 <a href="/wiki/Wikipedia:Community_portal" title="The hub for editors"><span>Community portal</span></a>,
 <a accesskey="r" href="/wiki/Special:RecentChanges" title="A list of recent changes to Wikipedia [r]"><span>Recent changes</span></a>,
 <a href="/wiki/Wikipedia:File_upload_wizard" title="Add images or other media for use on Wikipedia"><span>Upload file</span></a>,
 <a href="/wiki/Special:SpecialPages"><span>Special pages</span></a>,
 <a class="mw-logo" href="/wiki/Main_Page">
 <img alt="" aria-hidden="true" class="mw-logo-icon" height="50" src="/static/images/icons/wikipedia.png" width="50"/>
 <span class="mw-logo-container skin-invert">
 <img alt="Wikipedia" class="mw-logo-wordmark" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" style="width: 7.5em; height: 1.125em;"/>
 <img alt="The Free Encyclopedia" class="mw-logo-tagline" height="13" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" style="width: 7.3125em; height: 0.8125em;" width="117"/>
 </span>
 </a>,
 <a accesskey="f" class="cdx-button cdx-button--fake-button cdx-button--fake-button--enabled cdx-button--weight-quiet cdx-button--icon-only search-toggle" href="/wiki/Special:Search" title="Search Wikipedia [f]"><span class="vector-icon mw-ui-icon-search mw-ui-icon-wikimedia-search"></span>
 <span>Search</span>
 </a>,
 <a class="" data-mw="interface" href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>,
 <a class="" data-mw="interface" href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span>Create account</span></a>,
 <a accesskey="o" class="" data-mw="interface" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You're encouraged to log in; however, it's not mandatory. [o]"><span>Log in</span></a>,
 <a href="https://donate.wikimedia.org/?wmf_source=donate&amp;wmf_medium=sidebar&amp;wmf_campaign=en.wikipedia.org&amp;uselang=en"><span>Donate</span></a>,
 <a href="/w/index.php?title=Special:CreateAccount&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You are encouraged to create an account and log in; however, it is not mandatory"><span class="vector-icon mw-ui-icon-userAdd mw-ui-icon-wikimedia-userAdd"></span> <span>Create account</span></a>,
 <a accesskey="o" href="/w/index.php?title=Special:UserLogin&amp;returnto=List+of+largest+companies+in+the+United+States+by+revenue" title="You're encouraged to log in; however, it's not mandatory. [o]"><span class="vector-icon mw-ui-icon-logIn mw-ui-icon-wikimedia-logIn"></span> <span>Log in</span></a>,
 <a aria-label="Learn more about editing" href="/wiki/Help:Introduction"><span>learn more</span></a>,
 <a accesskey="y" href="/wiki/Special:MyContributions" title="A list of edits made from this IP address [y]"><span>Contributions</span></a>,
 <a accesskey="n" href="/wiki/Special:MyTalk" title="Discussion about edits from this IP address [n]"><span>Talk</span></a>,
 <a class="vector-toc-link" href="#">
 <div class="vector-toc-text">(Top)</div>
 </a>,
 <a class="vector-toc-link" href="#List_of_the_largest_public_/_publicly_traded_companies">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">1</span>
 <span>List of the largest public / publicly traded companies</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#List_of_largest_private_companies">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">2</span>
 <span>List of largest private companies</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#List_of_companies_by_profit">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">3</span>
 <span>List of companies by profit</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#See_also">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">4</span>
 <span>See also</span>
 </div>
 </a>,
 <a class="vector-toc-link" href="#References">
 <div class="vector-toc-text">
 <span class="vector-toc-numb">5</span>
 <span>References</span>
 </div>
 </a>,
 <a class="interlanguage-link-target" data-language-autonym="Deutsch" data-language-local-name="German" data-title="Liste der größten Unternehmen in den Vereinigten Staaten" href="https://de.wikipedia.org/wiki/Liste_der_gr%C3%B6%C3%9Ften_Unternehmen_in_den_Vereinigten_Staaten" hreflang="de" lang="de" title="Liste der größten Unternehmen in den Vereinigten Staaten – German"><span>Deutsch</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="فارسی" data-language-local-name="Persian" data-title="فهرست شرکت‌های آمریکایی" href="https://fa.wikipedia.org/wiki/%D9%81%D9%87%D8%B1%D8%B3%D8%AA_%D8%B4%D8%B1%DA%A9%D8%AA%E2%80%8C%D9%87%D8%A7%DB%8C_%D8%A2%D9%85%D8%B1%DB%8C%DA%A9%D8%A7%DB%8C%DB%8C" hreflang="fa" lang="fa" title="فهرست شرکت‌های آمریکایی – Persian"><span>فارسی</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Bahasa Indonesia" data-language-local-name="Indonesian" data-title="Daftar perusahaan Amerika Serikat" href="https://id.wikipedia.org/wiki/Daftar_perusahaan_Amerika_Serikat" hreflang="id" lang="id" title="Daftar perusahaan Amerika Serikat – Indonesian"><span>Bahasa Indonesia</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Nederlands" data-language-local-name="Dutch" data-title="Lijst van Amerikaanse ondernemingen" href="https://nl.wikipedia.org/wiki/Lijst_van_Amerikaanse_ondernemingen" hreflang="nl" lang="nl" title="Lijst van Amerikaanse ondernemingen – Dutch"><span>Nederlands</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="日本語" data-language-local-name="Japanese" data-title="アメリカ合衆国の企業一覧" href="https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%AB%E5%90%88%E8%A1%86%E5%9B%BD%E3%81%AE%E4%BC%81%E6%A5%AD%E4%B8%80%E8%A6%A7" hreflang="ja" lang="ja" title="アメリカ合衆国の企業一覧 – Japanese"><span>日本語</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="پنجابی" data-language-local-name="Western Punjabi" data-title="امریکی کمپنیان دی لسٹ" href="https://pnb.wikipedia.org/wiki/%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%DB%8C_%DA%A9%D9%85%D9%BE%D9%86%DB%8C%D8%A7%D9%86_%D8%AF%DB%8C_%D9%84%D8%B3%D9%B9" hreflang="pnb" lang="pnb" title="امریکی کمپنیان دی لسٹ – Western Punjabi"><span>پنجابی</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Português" data-language-local-name="Portuguese" data-title="Lista de maiores empresas dos Estados Unidos por receita" href="https://pt.wikipedia.org/wiki/Lista_de_maiores_empresas_dos_Estados_Unidos_por_receita" hreflang="pt" lang="pt" title="Lista de maiores empresas dos Estados Unidos por receita – Portuguese"><span>Português</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="Română" data-language-local-name="Romanian" data-title="Listă de companii din Statele Unite ale Americii" href="https://ro.wikipedia.org/wiki/List%C4%83_de_companii_din_Statele_Unite_ale_Americii" hreflang="ro" lang="ro" title="Listă de companii din Statele Unite ale Americii – Romanian"><span>Română</span></a>,
 <a class="interlanguage-link-target" data-language-autonym="اردو" data-language-local-name="Urdu" data-title="امریکی کمپنیوں کی فہرست" href="https://ur.wikipedia.org/wiki/%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%DB%8C_%DA%A9%D9%85%D9%BE%D9%86%DB%8C%D9%88%DA%BA_%DA%A9%DB%8C_%D9%81%DB%81%D8%B1%D8%B3%D8%AA" hreflang="ur" lang="ur" title="امریکی کمپنیوں کی فہرست – Urdu"><span>اردو</span></a>,
 <a class="wbc-editpage" href="https://www.wikidata.org/wiki/Special:EntityPage/Q1860802#sitelinks-wikipedia" title="Edit interlanguage links">Edit links</a>,
 <a accesskey="c" href="/wiki/List_of_largest_companies_in_the_United_States_by_revenue" title="View the content page [c]"><span>Article</span></a>,
 <a accesskey="t" href="/wiki/Talk:List_of_largest_companies_in_the_United_States_by_revenue" rel="discussion" title="Discuss improvements to the content page [t]"><span>Talk</span></a>,
 <a href="/wiki/List_of_largest_companies_in_the_United_States_by_revenue"><span>Read</span></a>,
 <a accesskey="e" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" title="Edit this page [e]"><span>Edit</span></a>,
 <a accesskey="h" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=history" title="Past revisions of this page [h]"><span>View history</span></a>,
 <a href="/wiki/List_of_largest_companies_in_the_United_States_by_revenue"><span>Read</span></a>,
 <a accesskey="e" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit" title="Edit this page [e]"><span>Edit</span></a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=history"><span>View history</span></a>,
 <a accesskey="j" href="/wiki/Special:WhatLinksHere/List_of_largest_companies_in_the_United_States_by_revenue" title="List of all English Wikipedia pages containing links to this page [j]"><span>What links here</span></a>,
 <a accesskey="k" href="/wiki/Special:RecentChangesLinked/List_of_largest_companies_in_the_United_States_by_revenue" rel="nofollow" title="Recent changes in pages linked from this page [k]"><span>Related changes</span></a>,
 <a accesskey="u" href="//en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard" title="Upload files [u]"><span>Upload file</span></a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;oldid=1311679947" title="Permanent link to this revision of this page"><span>Permanent link</span></a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=info" title="More information about this page"><span>Page information</span></a>,
 <a href="/w/index.php?title=Special:CiteThisPage&amp;page=List_of_largest_companies_in_the_United_States_by_revenue&amp;id=1311679947&amp;wpFormIdentifier=titleform" title="Information on how to cite this page"><span>Cite this page</span></a>,
 <a href="/w/index.php?title=Special:UrlShortener&amp;url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FList_of_largest_companies_in_the_United_States_by_revenue"><span>Get shortened URL</span></a>,
 <a href="/w/index.php?title=Special:QrCode&amp;url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FList_of_largest_companies_in_the_United_States_by_revenue"><span>Download QR code</span></a>,
 <a href="/w/index.php?title=Special:DownloadAsPdf&amp;page=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=show-download-screen" title="Download this page as a PDF file"><span>Download as PDF</span></a>,
 <a accesskey="p" href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;printable=yes" title="Printable version of this page [p]"><span>Printable version</span></a>,
 <a href="https://commons.wikimedia.org/wiki/Category:Companies_of_the_United_States" hreflang="en"><span>Wikimedia Commons</span></a>,
 <a accesskey="g" href="https://www.wikidata.org/wiki/Special:EntityPage/Q1860802" title="Structured data on this page hosted by Wikidata [g]"><span>Wikidata item</span></a>,
 <a href="/wiki/United_States" title="United States">United States</a>,
 <a href="/wiki/Revenue" title="Revenue">revenue</a>,
 <a href="/wiki/Fortune_500" title="Fortune 500"><i>Fortune</i> 500</a>,
 <a href="/wiki/Forbes" title="Forbes">Forbes</a>,
 <a href="/wiki/Public_company" title="Public company">publicly traded companies</a>,
 <a href="/wiki/Tax_inversion" title="Tax inversion">tax inversion</a>,
 <a href="/wiki/Privately_held_company" title="Privately held company">privately held companies</a>,
 <a href="/wiki/Cargill" title="Cargill">Cargill</a>,
 <a class="mw-redirect" href="/wiki/Koch_Industries" title="Koch Industries">Koch Industries</a>,
 <a href="/wiki/Government-sponsored_enterprise" title="Government-sponsored enterprise">government-sponsored enterprises</a>,
 <a href="/wiki/United_States_Congress" title="United States Congress">Congress</a>,
 <a href="/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&amp;action=edit&amp;section=1" title="Edit section: List of the largest public / publicly traded companies"><span>edit</span></a>,
 <a href="/wiki/Fiscal_year" title="Fiscal year">fiscal year</a>,
 <a href="/wiki/Fortune_500" title="Fortune 500"><i>Fortune</i> 500</a>,
 <a href="#cite_note-1"><span class="cite-bracket">[</span>1<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Walmart" title="Walmart">Walmart</a>,
 <a href="/wiki/Retail" title="Retail">Retail</a>,
 <a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>,
 <a href="/wiki/Amazon_(company)" title="Amazon (company)">Amazon</a>,
 <a href="/wiki/Cloud_computing" title="Cloud computing">cloud computing</a>,
 <a href="/wiki/Seattle" title="Seattle">Seattle, Washington</a>,
 <a href="/wiki/UnitedHealth_Group" title="UnitedHealth Group">UnitedHealth Group</a>,
 <a class="mw-redirect" href="/wiki/Healthcare" title="Healthcare">Healthcare</a>,
 <a href="/wiki/Minnetonka,_Minnesota" title="Minnetonka, Minnesota">Minnetonka, Minnesota</a>,
 <a class="mw-redirect" href="/wiki/Apple_Inc" title="Apple Inc">Apple</a>,
 <a href="/wiki/Electronics_industry" title="Electronics industry">Electronics industry</a>,
 <a href="/wiki/Cupertino,_California" title="Cupertino, California">Cupertino, California</a>,
 <a href="/wiki/CVS_Health" title="CVS Health">CVS Health</a>,
 <a href="/wiki/Woonsocket,_Rhode_Island" title="Woonsocket, Rhode Island">Woonsocket, Rhode Island</a>,
 <a href="/wiki/Berkshire_Hathaway" title="Berkshire Hathaway">Berkshire Hathaway</a>,
 <a href="/wiki/Conglomerate_(company)" title="Conglomerate (company)">Conglomerate</a>,
 <a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha, Nebraska</a>,
 <a class="mw-redirect" href="/wiki/Alphabet_Inc" title="Alphabet Inc">Alphabet</a>,
 <a href="/wiki/Technology" title="Technology">Technology</a>,
 <a href="/wiki/Mountain_View,_California" title="Mountain View, California">Mountain View, California</a>,
 <a href="/wiki/ExxonMobil" title="ExxonMobil">ExxonMobil</a>,
 <a href="/wiki/Petroleum_industry" title="Petroleum industry">Petroleum industry</a>,
 <a href="/wiki/Spring,_Texas" title="Spring, Texas">Spring, Texas</a>,
 <a href="/wiki/McKesson_Corporation" title="McKesson Corporation">McKesson Corporation</a>,
 <a href="/wiki/Irving,_Texas" title="Irving, Texas">Irving, Texas</a>,
 <a href="/wiki/Cencora" title="Cencora">Cencora</a>,
 <a href="/wiki/Pharmacy" title="Pharmacy">Pharmacy wholesale</a>,
 <a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken, Pennsylvania</a>,
 <a href="/wiki/JPMorgan_Chase" title="JPMorgan Chase">JPMorgan Chase</a>,
 <a href="/wiki/Financial_services" title="Financial services">Financial services</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City, New York</a>,
 <a href="/wiki/Costco" title="Costco">Costco</a>,
 <a href="/wiki/Issaquah,_Washington" title="Issaquah, Washington">Issaquah, Washington</a>,
 <a class="mw-redirect" href="/wiki/Cigna" title="Cigna">Cigna</a>,
 <a href="/wiki/Bloomfield,_Connecticut" title="Bloomfield, Connecticut">Bloomfield, Connecticut</a>,
 <a href="/wiki/Microsoft" title="Microsoft">Microsoft</a>,
 <a href="/wiki/Redmond,_Washington" title="Redmond, Washington">Redmond, Washington</a>,
 <a href="/wiki/Cardinal_Health" title="Cardinal Health">Cardinal Health</a>,
 <a href="/wiki/Dublin,_Ohio" title="Dublin, Ohio">Dublin, Ohio</a>,
 <a href="/wiki/Chevron_Corporation" title="Chevron Corporation">Chevron Corporation</a>,
 <a class="mw-redirect" href="/wiki/Houston,_Texas" title="Houston, Texas">Houston, Texas</a>,
 <a href="/wiki/Bank_of_America" title="Bank of America">Bank of America</a>,
 <a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte, North Carolina</a>,
 <a href="/wiki/General_Motors" title="General Motors">General Motors</a>,
 <a href="/wiki/Detroit" title="Detroit">Detroit, Michigan</a>,
 <a href="/wiki/Ford_Motor_Company" title="Ford Motor Company">Ford Motor Company</a>,
 <a href="/wiki/Automotive_industry" title="Automotive industry">Automotive industry</a>,
 <a href="/wiki/Dearborn,_Michigan" title="Dearborn, Michigan">Dearborn, Michigan</a>,
 <a class="mw-redirect" href="/wiki/Anthem_(company)" title="Anthem (company)">Elevance Health</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis, Indiana</a>,
 <a href="/wiki/Citigroup" title="Citigroup">Citigroup</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City, New York</a>,
 <a href="/wiki/Meta_Platforms" title="Meta Platforms">Meta Platforms</a>,
 <a href="/wiki/Menlo_Park,_California" title="Menlo Park, California">Menlo Park, California</a>,
 <a class="mw-redirect" href="/wiki/Centene" title="Centene">Centene</a>,
 <a href="/wiki/St._Louis" title="St. Louis">St. Louis, Missouri</a>,
 <a class="mw-redirect" href="/wiki/The_Home_Depot" title="The Home Depot">The Home Depot</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta, Georgia</a>,
 <a href="/wiki/Fannie_Mae" title="Fannie Mae">Fannie Mae</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington, D.C.</a>,
 <a href="/wiki/Walgreens_Boots_Alliance" title="Walgreens Boots Alliance">Walgreens Boots Alliance</a>,
 <a href="/wiki/Deerfield,_Illinois" title="Deerfield, Illinois">Deerfield, Illinois</a>,
 <a href="/wiki/Kroger" title="Kroger">Kroger</a>,
 <a href="/wiki/Cincinnati" title="Cincinnati">Cincinnati, Ohio</a>,
 <a href="/wiki/Phillips_66" title="Phillips 66">Phillips 66</a>,
 <a href="/wiki/Houston" title="Houston">Houston, Texas</a>,
 <a href="/wiki/Marathon_Petroleum" title="Marathon Petroleum">Marathon Petroleum</a>,
 <a href="/wiki/Findlay,_Ohio" title="Findlay, Ohio">Findlay, Ohio</a>,
 <a class="mw-redirect" href="/wiki/Verizon_Communications" title="Verizon Communications">Verizon Communications</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City, New York</a>,
 <a href="/wiki/Nvidia" title="Nvidia">Nvidia</a>,
 <a href="/wiki/Santa_Clara,_California" title="Santa Clara, California">Santa Clara, California</a>,
 <a href="/wiki/Goldman_Sachs" title="Goldman Sachs">Goldman Sachs</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City, New York</a>,
 <a href="/wiki/Wells_Fargo" title="Wells Fargo">Wells Fargo</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco, California</a>,
 <a href="/wiki/Valero_Energy" title="Valero Energy">Valero Energy</a>,
 <a href="/wiki/San_Antonio" title="San Antonio">San Antonio, Texas</a>,
 <a href="/wiki/Comcast" title="Comcast">Comcast</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia, Pennsylvania</a>,

In [8]:
for link in all_a:
    print(link.get('href'))

#bodyContent
/wiki/Main_Page
/wiki/Wikipedia:Contents
/wiki/Portal:Current_events
/wiki/Special:Random
/wiki/Wikipedia:About
//en.wikipedia.org/wiki/Wikipedia:Contact_us
/wiki/Help:Contents
/wiki/Help:Introduction
/wiki/Wikipedia:Community_portal
/wiki/Special:RecentChanges
/wiki/Wikipedia:File_upload_wizard
/wiki/Special:SpecialPages
/wiki/Main_Page
/wiki/Special:Search
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
/w/index.php?title=Special:CreateAccount&returnto=List+of+largest+companies+in+the+United+States+by+revenue
/w/index.php?title=Special:UserLogin&returnto=List+of+largest+companies+in+the+United+States+by+revenue
https://donate.wikimedia.org/?wmf_source=donate&wmf_medium=sidebar&wmf_campaign=en.wikipedia.org&uselang=en
/w/index.php?title=Special:CreateAccount&returnto=List+of+largest+companies+in+the+United+States+by+revenue
/w/index.php?title=Special:UserLogin&returnto=List+of+largest+companies+in+the+United+States+by+revenue
/wiki/Help:Introduction
/wiki/Special:MyContributions
/wiki/Special:MyTalk
#
#List_of_the_largest_public_/_publicly_traded_companies
#List_of_largest_private_companies
#List_of_companies_by_profit
#See_also
#References
https://de.wikipedia.org/wiki/Liste_der_gr%C3%B6%C3%9Ften_Unternehmen_in_den_Vereinigten_Staaten
https://fa.wikipedia.org/wiki/%D9%81%D9%87%D8%B1%D8%B3%D8%AA_%D8%B4%D8%B1%DA%A9%D8%AA%E2%80%8C%D9%87%D8%A7%DB%8C_%D8%A2%D9%85%D8%B1%DB%8C%DA%A9%D8%A7%DB%8C%DB%8C
https://id.wikipedia.org/wiki/Daftar_perusahaan_Amerika_Serikat
https://nl.wikipedia.org/wiki/Lijst_van_Amerikaanse_ondernemingen
https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%A1%E3%83%AA%E3%82%AB%E5%90%88%E8%A1%86%E5%9B%BD%E3%81%AE%E4%BC%81%E6%A5%AD%E4%B8%80%E8%A6%A7
https://pnb.wikipedia.org/wiki/%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%DB%8C_%DA%A9%D9%85%D9%BE%D9%86%DB%8C%D8%A7%D9%86_%D8%AF%DB%8C_%D9%84%D8%B3%D9%B9
https://pt.wikipedia.org/wiki/Lista_de_maiores_empresas_dos_Estados_Unidos_por_receita
https://ro.wikipedia.org/wiki/List%C4%83_de_companii_din_Statele_Unite_ale_Americii
https://ur.wikipedia.org/wiki/%D8%A7%D9%85%D8%B1%DB%8C%DA%A9%DB%8C_%DA%A9%D9%85%D9%BE%D9%86%DB%8C%D9%88%DA%BA_%DA%A9%DB%8C_%D9%81%DB%81%D8%B1%D8%B3%D8%AA
https://www.wikidata.org/wiki/Special:EntityPage/Q1860802#sitelinks-wikipedia
/wiki/List_of_largest_companies_in_the_United_States_by_revenue
/wiki/Talk:List_of_largest_companies_in_the_United_States_by_revenue
/wiki/List_of_largest_companies_in_the_United_States_by_revenue
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=history
/wiki/List_of_largest_companies_in_the_United_States_by_revenue
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=history
/wiki/Special:WhatLinksHere/List_of_largest_companies_in_the_United_States_by_revenue
/wiki/Special:RecentChangesLinked/List_of_largest_companies_in_the_United_States_by_revenue
//en.wikipedia.org/wiki/Wikipedia:File_Upload_Wizard
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&oldid=1311679947
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=info
/w/index.php?title=Special:CiteThisPage&page=List_of_largest_companies_in_the_United_States_by_revenue&id=1311679947&wpFormIdentifier=titleform
/w/index.php?title=Special:UrlShortener&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FList_of_largest_companies_in_the_United_States_by_revenue
/w/index.php?title=Special:QrCode&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FList_of_largest_companies_in_the_United_States_by_revenue
/w/index.php?title=Special:DownloadAsPdf&page=List_of_largest_companies_in_the_United_States_by_revenue&action=show-download-screen
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&printable=yes
https://commons.wikimedia.org/wiki/Category:Companies_of_the_United_States
https://www.wikidata.org/wiki/Special:EntityPage/Q1860802
/wiki/United_States
/wiki/Revenue
/wiki/Fortune_500
/wiki/Forbes
/wiki/Public_company
/wiki/Tax_inversion
/wiki/Privately_held_company
/wiki/Cargill
/wiki/Koch_Industries
/wiki/Government-sponsored_enterprise
/wiki/United_States_Congress
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit&section=1
/wiki/Fiscal_year
/wiki/Fortune_500
#cite_note-1
/wiki/Walmart
/wiki/Retail
/wiki/Bentonville,_Arkansas
/wiki/Amazon_(company)
/wiki/Cloud_computing
/wiki/Seattle
/wiki/UnitedHealth_Group
/wiki/Healthcare
/wiki/Minnetonka,_Minnesota
/wiki/Apple_Inc
/wiki/Electronics_industry
/wiki/Cupertino,_California
/wiki/CVS_Health
/wiki/Woonsocket,_Rhode_Island
/wiki/Berkshire_Hathaway
/wiki/Conglomerate_(company)
/wiki/Omaha,_Nebraska
/wiki/Alphabet_Inc
/wiki/Technology
/wiki/Mountain_View,_California
/wiki/ExxonMobil
/wiki/Petroleum_industry
/wiki/Spring,_Texas
/wiki/McKesson_Corporation
/wiki/Irving,_Texas
/wiki/Cencora
/wiki/Pharmacy
/wiki/Conshohocken,_Pennsylvania
/wiki/JPMorgan_Chase
/wiki/Financial_services
/wiki/New_York_City
/wiki/Costco
/wiki/Issaquah,_Washington
/wiki/Cigna
/wiki/Bloomfield,_Connecticut
/wiki/Microsoft
/wiki/Redmond,_Washington
/wiki/Cardinal_Health
/wiki/Dublin,_Ohio
/wiki/Chevron_Corporation
/wiki/Houston,_Texas
/wiki/Bank_of_America
/wiki/Charlotte,_North_Carolina
/wiki/General_Motors
/wiki/Detroit
/wiki/Ford_Motor_Company
/wiki/Automotive_industry
/wiki/Dearborn,_Michigan
/wiki/Anthem_(company)
/wiki/Indianapolis
/wiki/Citigroup
/wiki/New_York_City
/wiki/Meta_Platforms
/wiki/Menlo_Park,_California
/wiki/Centene
/wiki/St._Louis
/wiki/The_Home_Depot
/wiki/Atlanta
/wiki/Fannie_Mae
/wiki/Washington,_D.C.
/wiki/Walgreens_Boots_Alliance
/wiki/Deerfield,_Illinois
/wiki/Kroger
/wiki/Cincinnati
/wiki/Phillips_66
/wiki/Houston
/wiki/Marathon_Petroleum
/wiki/Findlay,_Ohio
/wiki/Verizon_Communications
/wiki/New_York_City
/wiki/Nvidia
/wiki/Santa_Clara,_California
/wiki/Goldman_Sachs
/wiki/New_York_City
/wiki/Wells_Fargo
/wiki/San_Francisco
/wiki/Valero_Energy
/wiki/San_Antonio
/wiki/Comcast
/wiki/Philadelphia
/wiki/State_Farm
/wiki/Bloomington,_Illinois
/wiki/AT%26T
/wiki/Conglomerate_(company)
/wiki/Dallas
/wiki/Freddie_Mac
/wiki/McLean,_Virginia
/wiki/Humana
/wiki/Louisville,_Kentucky
/wiki/Morgan_Stanley
/wiki/New_York_City
/wiki/Target_Corporation
/wiki/Minneapolis
/wiki/StoneX_Group
/wiki/New_York_City
/wiki/Tesla_Inc
/wiki/Austin,_Texas
/wiki/Dell_Technologies
/wiki/Round_Rock,_Texas
/wiki/PepsiCo
/wiki/Drink
/wiki/Purchase,_New_York
/wiki/The_Walt_Disney_Company
/wiki/Burbank,_California
/wiki/United_Parcel_Service
/wiki/Transportation
/wiki/Atlanta
/wiki/Johnson_%26_Johnson
/wiki/New_Brunswick,_New_Jersey
/wiki/FedEx
/wiki/Memphis,_Tennessee
/wiki/Archer_Daniels_Midland
/wiki/Food_industry
/wiki/Chicago,_Illinois
/wiki/Procter_%26_Gamble
/wiki/Cincinnati
/wiki/Lowe%27s
/wiki/Mooresville,_North_Carolina
/wiki/Energy_Transfer_Partners
/wiki/Dallas,_Texas
/wiki/RTX_Corporation
/wiki/Arlington_County,_Virginia
/wiki/Albertsons
/wiki/Boise,_Idaho
/wiki/Sysco
/wiki/Houston,_Texas
/wiki/Progressive_Corporation
/wiki/Mayfield_Village,_Ohio
/wiki/American_Express
/wiki/New_York_City
/wiki/Lockheed_Martin
/wiki/Bethesda,_Maryland
/wiki/MetLife
/wiki/New_York_City
/wiki/HCA_Healthcare
/wiki/Nashville,_Tennessee
/wiki/Prudential_Financial
/wiki/Newark,_New_Jersey
/wiki/Boeing
/wiki/Aerospace_engineering
/wiki/Arms_industry
/wiki/Arlington_County
/wiki/Caterpillar_Inc
/wiki/Irving,_Texas
/wiki/Merck_%26_Co.
/wiki/Kenilworth,_New_Jersey
/wiki/Allstate
/wiki/Northfield_Township,_Cook_County,_Illinois
/wiki/Pfizer
/wiki/New_York_City
/wiki/IBM
/wiki/Armonk,_New_York
/wiki/New_York_Life_Insurance_Company
/wiki/New_York_City
/wiki/Delta_Air_Lines
/wiki/Airline
/wiki/Atlanta_Georgia
/wiki/Publix
/wiki/Lakeland,_Florida
/wiki/Nationwide_Mutual_Insurance_Company
/wiki/Columbus,_Ohio
/wiki/TD_Synnex
/wiki/Information_Technology
/wiki/Clearwater,_Florida
/wiki/United_Airlines
/wiki/Chicago_Illinois
/wiki/ConocoPhillips
/wiki/Houston,_Texas
/wiki/TJX
/wiki/Framingham,_Massachusetts
/wiki/AbbVie
/wiki/Lake_Bluff,_Illinois
/wiki/Enterprise_Products
/wiki/Houston,_Texas
/wiki/Charter_Communications
/wiki/Stamford,_Connecticut
/wiki/Performance_Food_Group
/wiki/Richmond,_Virginia
/wiki/American_Airlines
/wiki/Fort_Worth,_Texas
/wiki/Capital_One_Financial
/wiki/Richmond,_Virginia
/wiki/Cisco
/wiki/San_Jose,_California
/wiki/HP_Inc
/wiki/Palo_Alto,_California
/wiki/Tyson_Foods
/wiki/Springdale,_Arkansas
/wiki/Intel
/wiki/Santa_Clara,_California
/wiki/Oracle_Corporation
/wiki/Austin,_Texas
/wiki/Broadcom
/wiki/Palo_Alto,_California
/wiki/John_Deere
/wiki/Moline,_Illinois
/wiki/Nike_Inc
/wiki/Beaverton,_Oregon
/wiki/Liberty_Mutual
/wiki/Boston
/wiki/Plains_All_American_Pipeline
/wiki/Houston,_Texas
/wiki/USAA
/wiki/San_Antonio,_Texas
/wiki/Bristol-Myers_Squibb
/wiki/New_York_City
/wiki/New_York_(state)
/wiki/Ingram_Micro
/wiki/Irvine,_California
/wiki/General_Dynamics
/wiki/Reston,_Virginia
/wiki/Coca-Cola_company
/wiki/Atlanta_Georgia
/wiki/TIAA
/wiki/New_York_City
/wiki/The_Travelers_Companies
/wiki/New_York_City
/wiki/Eli_Lilly_and_Company
/wiki/Indianapolis,_Indiana
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit&section=2
/wiki/Forbes
#cite_note-2
/wiki/Cargill
/wiki/Minnetonka,_Minnesota
/wiki/Koch_Industries
/wiki/Wichita,_Kansas
/wiki/Publix_Super_Markets
/wiki/Mars,_Incorporated
/wiki/McLean,_Virginia
/wiki/H-E-B
/wiki/San_Antonio,_Texas
/wiki/Reyes_Holdings
/wiki/Wholesaling
/wiki/Rosemont,_Illinois
/wiki/Enterprise_Holdings
/wiki/Car_rental
/wiki/Clayton,_Missouri
/wiki/C%26S_Wholesale_Grocers
/wiki/Keene,_New_Hampshire
/wiki/Love%27s
/wiki/Oklahoma_City,_Oklahoma
/wiki/Southern_Glazer%27s_Wine_and_Spirits
/wiki/Miramar,_Florida
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit&section=3
#cite_note-3
/wiki/Alphabet_Inc.
/wiki/Apple_Inc.
/wiki/Berkshire_Hathaway
/wiki/Microsoft
/wiki/Nvidia
/wiki/Meta_Platforms
/wiki/Amazon_(company)
/wiki/JPMorgan_Chase
/wiki/ExxonMobil
/wiki/Bank_of_America
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit&section=4
/wiki/List_of_companies_of_the_United_States_by_state
/wiki/List_of_largest_companies_by_revenue
/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&action=edit&section=5
#cite_ref-1
https://fortune.com/ranking/fortune500/search/
#cite_ref-2
https://www.forbes.com/lists/largest-private-companies/
#cite_ref-3
https://fortune.com/ranking/global500/2023/search/?fg500_country=U.S.
https://en.wikipedia.org/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&oldid=1311679947
/wiki/Help:Category
/wiki/Category:Economy_of_the_United_States-related_lists
/wiki/Category:Lists_of_companies_by_revenue
/wiki/Category:Lists_of_largest_private_companies_by_country
/wiki/Category:Lists_of_companies_of_the_United_States
/wiki/Category:Articles_with_short_description
/wiki/Category:Short_description_is_different_from_Wikidata
/wiki/Category:Use_mdy_dates_from_April_2025
/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License
https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Terms_of_Use
https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Privacy_policy
https://wikimediafoundation.org/
https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Privacy_policy
/wiki/Wikipedia:About
/wiki/Wikipedia:General_disclaimer
//en.wikipedia.org/wiki/Wikipedia:Contact_us
https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Universal_Code_of_Conduct
https://developer.wikimedia.org
https://stats.wikimedia.org/#/en.wikipedia.org
https://foundation.wikimedia.org/wiki/Special:MyLanguage/Policy:Cookie_statement
//en.wikipedia.org/w/index.php?title=List_of_largest_companies_in_the_United_States_by_revenue&mobileaction=toggle_view_mobile
https://www.wikimedia.org/
https://www.mediawiki.org/
#
#
#
#
#
#
#
#
#

## Table

In [10]:
all_tables = soup.find_all('table') 
print('Total number of tables:',len(all_tables)) 
table = all_tables[0]

Total number of tables: 3

In [11]:
world_titles = table.find_all('th')
world_titles

[<th>Rank
 </th>,
 <th>Name
 </th>,
 <th>Industry
 </th>,
 <th>Revenue <br/>(USD millions)
 </th>,
 <th>Revenue growth
 </th>,
 <th>Employees
 </th>,
 <th>Headquarters
 </th>]

In [12]:
len(world_titles)

7

In [13]:
world_titles[1].text.strip()

'Name'

In [14]:
world_table_titles = [title.text.strip() for title in world_titles]
world_table_titles

['Rank',
 'Name',
 'Industry',
 'Revenue (USD millions)',
 'Revenue growth',
 'Employees',
 'Headquarters']

In [15]:
df = pd.DataFrame(columns = world_table_titles)
df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [16]:
column_data = table.find_all('tr')

In [17]:
row_data = column_data[1:][0].find_all('td')
row_data

[<td>1
 </td>,
 <td><a href="/wiki/Walmart" title="Walmart">Walmart</a>
 </td>,
 <td><a href="/wiki/Retail" title="Retail">Retail</a>
 </td>,
 <td style="text-align:center;">680,985
 </td>,
 <td style="text-align:center;"><span typeof="mw:File"><span title="Increase"><img alt="Increase" class="mw-file-element" data-file-height="300" data-file-width="300" decoding="async" height="11" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/20px-Increase2.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Increase2.svg/40px-Increase2.svg.png 2x" width="11"/></span></span> <span data-sort-value="7000300000000000000♠" style="display:none"></span> 5.1%
 </td>,
 <td style="text-align:center;">2,100,000
 </td>,
 <td><a href="/wiki/Bentonville,_Arkansas" title="Bentonville, Arkansas">Bentonville, Arkansas</a>
 </td>]

In [18]:
row_data[1].text.strip()

'Walmart'

In [19]:
for row in column_data[1:]:
    row_data = row.find_all('td')
    individual_row_data = [data.text.strip() for data in row_data]
    
    length = len(df)
    df.loc[length] = individual_row_data

In [20]:
df

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Electronics industry,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
...,...,...,...,...,...,...,...
95,96,General Dynamics,Aerospace and defense,"47,716",12.9%,"117,000","Reston, Virginia"
96,97,Coca-Cola,Beverage,"47,061",2.9%,"69,700","Atlanta, Georgia"
97,98,TIAA,Financials,"46,946",2.6%,"15,623","New York City, New York"
98,99,The Travelers Companies,Insurance,"46,423",12.2%,"34,000","New York City, New York"
99,100,Eli Lilly,Pharmaceutical industry,"45,043",32.0%,"47,000","Indianapolis, Indiana"