In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
URL = "https://realpython.github.io/fake-jobs/"
page = requests.get(URL)
soup = BeautifulSoup(page.content, "html.parser")

In [3]:
results = soup.find(id="ResultsContainer")

In [4]:
cards = results.find_all("div", class_="card-content")
len(cards)

100

In [5]:
cards[0].find("h2", class_="title").text.strip()

'Senior Python Developer'

In [6]:
cards[0].find("h3", class_="company").text.strip()

'Payne, Roberts and Davis'

In [7]:
cards[0].find("p", class_="location").text.strip()

'Stewartbury, AA'

In [8]:
for card in cards:
    title = card.find("h2", class_="title")
    company = card.find("h3", class_="company")
    location = card.find("p", class_="location")
    print(title.text.strip())
    print(company.text.strip())
    print(location.text.strip())
    print()

Senior Python Developer
Payne, Roberts and Davis
Stewartbury, AA

Energy engineer
Vasquez-Davidson
Christopherville, AA

Legal executive
Jackson, Chambers and Levy
Port Ericaburgh, AA

Fitness centre manager
Savage-Bradley
East Seanview, AP

Product manager
Ramirez Inc
North Jamieview, AP

Medical technical officer
Rogers-Yates
Davidville, AP

Physiological scientist
Kramer-Klein
South Christopher, AE

Textile designer
Meyers-Johnson
Port Jonathan, AE

Television floor manager
Hughes-Williams
Osbornetown, AE

Waste management officer
Jones, Williams and Villa
Scotttown, AP

Software Engineer (Python)
Garcia PLC
Ericberg, AE

Interpreter
Gregory and Sons
Ramireztown, AE

Architect
Clark, Garcia and Sosa
Figueroaview, AA

Meteorologist
Bush PLC
Kelseystad, AA

Audiological scientist
Salazar-Meyers
Williamsburgh, AE

English as a second language teacher
Parker, Murphy and Brooks
Mitchellburgh, AE

Surgeon
Cruz-Brown
West Jessicabury, AA

Equities trader
Macdonald-Ferguson
Maloneshire, AE

Newspaper journalist
Williams, Peterson and Rojas
Johnsonton, AA

Materials engineer
Smith and Sons
South Davidtown, AP

Python Programmer (Entry-Level)
Moss, Duncan and Allen
Port Sara, AE

Product/process development scientist
Gomez-Carroll
Marktown, AA

Scientist, research (maths)
Manning, Welch and Herring
Laurenland, AE

Ecologist
Lee, Gutierrez and Brown
Lauraton, AP

Materials engineer
Davis, Serrano and Cook
South Tammyberg, AP

Historic buildings inspector/conservation officer
Smith LLC
North Brandonville, AP

Data scientist
Thomas Group
Port Robertfurt, AA

Psychiatrist
Silva-King
Burnettbury, AE

Structural engineer
Pierce-Long
Herbertside, AA

Immigration officer
Walker-Simpson
Christopherport, AP

Python Programmer (Entry-Level)
Cooper and Sons
West Victor, AE

Neurosurgeon
Donovan, Gonzalez and Figueroa
Port Aaron, AP

Broadcast engineer
Morgan, Butler and Bennett
Loribury, AA

Make
Snyder-Lee
Angelastad, AP

Nurse, adult
Harris PLC
Larrytown, AE

Air broker
Washington PLC
West Colin, AP

Editor, film/video
Brown, Price and Campbell
West Stephanie, AP

Production assistant, radio
Mcgee PLC
Laurentown, AP

Engineer, communications
Dixon Inc
Wrightberg, AP

Sales executive
Thompson, Sheppard and Ward
Alberttown, AE

Software Developer (Python)
Adams-Brewer
Brockburgh, AE

Futures trader
Schneider-Brady
North Jason, AE

Tour manager
Gonzales-Frank
Arnoldhaven, AE

Cytogeneticist
Smith-Wong
Lake Destiny, AP

Designer, multimedia
Pierce-Herrera
South Timothyburgh, AP

Trade union research officer
Aguilar, Rivera and Quinn
New Jimmyton, AE

Chemist, analytical
Lowe, Barnes and Thomas
New Lucasbury, AP

Programmer, multimedia
Lewis, Gonzalez and Vasquez
Port Cory, AE

Engineer, broadcasting (operations)
Taylor PLC
Gileston, AA

Teacher, primary school
Oliver, Jones and Ramirez
Cindyshire, AA

Python Developer
Rivera and Sons
East Michaelfort, AA

Manufacturing systems engineer
Garcia PLC
Joybury, AE

Producer, television/film/video
Johnson, Wells and Kramer
Emmatown, AE

Scientist, forensic
Gonzalez LLC
Colehaven, AP

Bonds trader
Morgan, White and Macdonald
Port Coryton, AE

Editorial assistant
Robinson-Fitzpatrick
Amyborough, AA

Photographer
Waters, Wilson and Hoover
Reynoldsville, AA

Retail banker
Hill LLC
Port Billy, AP

Jewellery designer
Li-Gregory
Adamburgh, AA

Ophthalmologist
Fisher, Ryan and Coleman
Wilsonmouth, AA

Back-End Web Developer (Python, Django)
Stewart-Alexander
South Kimberly, AA

Licensed conveyancer
Abbott and Sons
Benjaminland, AP

Futures trader
Bryant, Santana and Davenport
Zacharyport, AA

Counselling psychologist
Smith PLC
Port Devonville, AE

Insurance underwriter
Patterson-Singh
East Thomas, AE

Engineer, automotive
Martinez-Berry
New Jeffrey, AP

Producer, radio
May, Taylor and Fisher
Davidside, AA

Dispensing optician
Bailey, Owen and Thompson
Jamesville, AA

Designer, fashion/clothing
Vasquez Ltd
New Kelly, AP

Chartered loss adjuster
Leblanc LLC
Lake Antonio, AA

Back-End Web Developer (Python, Django)
Jackson, Ali and Mckee
New Elizabethside, AA

Forest/woodland manager
Blankenship, Knight and Powell
Millsbury, AE

Clinical cytogeneticist
Patton, Haynes and Jones
Lloydton, AP

Print production planner
Wood Inc
Port Jeremy, AA

Systems developer
Collins Group
New Elizabethtown, AA

Graphic designer
Flores-Nelson
Charlesstad, AE

Writer
Mitchell, Jones and Olson
Josephbury, AE

Field seismologist
Howard Group
Seanfurt, AA

Chief Strategy Officer
Kramer-Edwards
Williambury, AA

Air cabin crew
Berry-Houston
South Jorgeside, AP

Python Programmer (Entry-Level)
Mathews Inc
Robertborough, AP

Warden/ranger
Riley-Johnson
South Saratown, AP

Sports therapist
Spencer and Sons
Hullview, AA

Arts development officer
Camacho-Sanchez
Philipland, AP

Printmaker
Oliver and Sons
North Patty, AE

Health and safety adviser
Eaton PLC
North Stephen, AE

Manufacturing systems engineer
Stanley-Frederick
Stevensland, AP

Programmer, applications
Bradley LLC
Reyesstad, AE

Medical physicist
Parker, Goodwin and Zavala
Bellberg, AP

Media planner
Kim-Miles
North Johnland, AE

Software Developer (Python)
Moreno-Rodriguez
Martinezburgh, AE

Surveyor, land/geomatics
Brown-Ortiz
Joshuatown, AE

Legal executive
Hartman PLC
West Ericstad, AA

Librarian, academic
Brooks Inc
Tuckertown, AE

Barrister
Washington-Castillo
Perezton, AE

Museum/gallery exhibitions officer
Nguyen, Yoder and Petty
Lake Abigail, AE

Radiographer, diagnostic
Holder LLC
Jacobshire, AP

Database administrator
Yates-Ferguson
Port Susan, AE

Furniture designer
Ortega-Lawrence
North Tiffany, AA

Ship broker
Fuentes, Walls and Castro
Michelleville, AP

In [9]:
titles = []
companies = []
locations = []

for card in cards:
    title = card.find("h2", class_="title")
    company = card.find("h3", class_="company")
    location = card.find("p", class_="location")
    
    titles.append(title.text.strip() if title else None)
    companies.append(company.text.strip() if company else None)
    locations.append(location.text.strip() if location else None)

df = pd.DataFrame({
    'Title': titles,
    'Company': companies,
    'Location': locations
})

df

,Title,Company,Location
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA"
1,Energy engineer,Vasquez-Davidson,"Christopherville, AA"
2,Legal executive,"Jackson, Chambers and Levy","Port Ericaburgh, AA"
3,Fitness centre manager,Savage-Bradley,"East Seanview, AP"
4,Product manager,Ramirez Inc,"North Jamieview, AP"
...,...,...,...
95,Museum/gallery exhibitions officer,"Nguyen, Yoder and Petty","Lake Abigail, AE"
96,"Radiographer, diagnostic",Holder LLC,"Jacobshire, AP"
97,Database administrator,Yates-Ferguson,"Port Susan, AE"
98,Furniture designer,Ortega-Lawrence,"North Tiffany, AA"
99,Ship broker,"Fuentes, Walls and Castro","Michelleville, AP"

In [10]:
python_jobs = results.find_all("h2", string="Python")
python_jobs

[]

In [11]:
python_jobs = results.find_all(
    "h2", string=lambda text: "python" in text.lower()
)
python_jobs

[<h2 class="title is-5">Senior Python Developer</h2>,
 <h2 class="title is-5">Software Engineer (Python)</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Software Developer (Python)</h2>,
 <h2 class="title is-5">Python Developer</h2>,
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>,
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>,
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>,
 <h2 class="title is-5">Software Developer (Python)</h2>]

In [12]:
python_jobs[0].parent.parent.parent

<div class="card-content">
<div class="media">
<div class="media-left">
<figure class="image is-48x48">
<img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
</figure>
</div>
<div class="media-content">
<h2 class="title is-5">Senior Python Developer</h2>
<h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>
</div>
</div>
<div class="content">
<p class="location">
        Stewartbury, AA
      </p>
<p class="is-small has-text-grey">
<time datetime="2021-04-08">2021-04-08</time>
</p>
</div>
<footer class="card-footer">
<a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
<a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">Apply</a>
</footer>
</div>

In [13]:
python_job_cards = [h2_element.parent.parent.parent for h2_element in python_jobs]
python_job_cards

[<div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Senior Python Developer</h2>
 <h3 class="subtitle is-6 company">Payne, Roberts and Davis</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         Stewartbury, AA
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Software Engineer (Python)</h2>
 <h3 class="subtitle is-6 company">Garcia PLC</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         Ericberg, AE
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>
 <h3 class="subtitle is-6 company">Moss, Duncan and Allen</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         Port Sara, AE
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>
 <h3 class="subtitle is-6 company">Cooper and Sons</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         West Victor, AE
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Software Developer (Python)</h2>
 <h3 class="subtitle is-6 company">Adams-Brewer</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         Brockburgh, AE
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-developer-python-40.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Python Developer</h2>
 <h3 class="subtitle is-6 company">Rivera and Sons</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         East Michaelfort, AA
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-developer-50.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>
 <h3 class="subtitle is-6 company">Stewart-Alexander</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         South Kimberly, AA
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Back-End Web Developer (Python, Django)</h2>
 <h3 class="subtitle is-6 company">Jackson, Ali and Mckee</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         New Elizabethside, AA
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Python Programmer (Entry-Level)</h2>
 <h3 class="subtitle is-6 company">Mathews Inc</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         Robertborough, AP
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80.html" target="_blank">Apply</a>
 </footer>
 </div>,
 <div class="card-content">
 <div class="media">
 <div class="media-left">
 <figure class="image is-48x48">
 <img alt="Real Python Logo" src="https://files.realpython.com/media/real-python-logo-thumbnail.7f0db70c2ed2.jpg?__no_cf_polish=1"/>
 </figure>
 </div>
 <div class="media-content">
 <h2 class="title is-5">Software Developer (Python)</h2>
 <h3 class="subtitle is-6 company">Moreno-Rodriguez</h3>
 </div>
 </div>
 <div class="content">
 <p class="location">
         Martinezburgh, AE
       </p>
 <p class="is-small has-text-grey">
 <time datetime="2021-04-08">2021-04-08</time>
 </p>
 </div>
 <footer class="card-footer">
 <a class="card-footer-item" href="https://www.realpython.com" target="_blank">Learn</a>
 <a class="card-footer-item" href="https://realpython.github.io/fake-jobs/jobs/software-developer-python-90.html" target="_blank">Apply</a>
 </footer>
 </div>]

In [14]:
titles = []
companies = []
locations = []

for card in python_job_cards:
    title = card.find("h2", class_="title")
    company = card.find("h3", class_="company")
    location = card.find("p", class_="location")
    
    titles.append(title.text.strip() if title else None)
    companies.append(company.text.strip() if company else None)
    locations.append(location.text.strip() if location else None)

df = pd.DataFrame({
    'Title': titles,
    'Company': companies,
    'Location': locations
})

df

,Title,Company,Location
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA"
1,Software Engineer (Python),Garcia PLC,"Ericberg, AE"
2,Python Programmer (Entry-Level),"Moss, Duncan and Allen","Port Sara, AE"
3,Python Programmer (Entry-Level),Cooper and Sons,"West Victor, AE"
4,Software Developer (Python),Adams-Brewer,"Brockburgh, AE"
5,Python Developer,Rivera and Sons,"East Michaelfort, AA"
6,"Back-End Web Developer (Python, Django)",Stewart-Alexander,"South Kimberly, AA"
7,"Back-End Web Developer (Python, Django)","Jackson, Ali and Mckee","New Elizabethside, AA"
8,Python Programmer (Entry-Level),Mathews Inc,"Robertborough, AP"
9,Software Developer (Python),Moreno-Rodriguez,"Martinezburgh, AE"

In [15]:
for job_card in python_job_cards:
    links = job_card.find_all("a")
    for link in links:
        print(link.text.strip())

Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply
Learn
Apply

In [16]:
for job_card in python_job_cards:
    links = job_card.find_all("a")
    for link in links:
        url = link["href"]
        print(f"Apply here: {url}")

Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/software-developer-python-40.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/python-developer-50.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80.html
Apply here: https://www.realpython.com
Apply here: https://realpython.github.io/fake-jobs/jobs/software-developer-python-90.html

In [17]:
for job_card in python_job_cards:
    url = job_card.find_all("a")[1]["href"]
    print(f"Apply here: {url}")

Apply here: https://realpython.github.io/fake-jobs/jobs/senior-python-developer-0.html
Apply here: https://realpython.github.io/fake-jobs/jobs/software-engineer-python-10.html
Apply here: https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-20.html
Apply here: https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-30.html
Apply here: https://realpython.github.io/fake-jobs/jobs/software-developer-python-40.html
Apply here: https://realpython.github.io/fake-jobs/jobs/python-developer-50.html
Apply here: https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-60.html
Apply here: https://realpython.github.io/fake-jobs/jobs/back-end-web-developer-python-django-70.html
Apply here: https://realpython.github.io/fake-jobs/jobs/python-programmer-entry-level-80.html
Apply here: https://realpython.github.io/fake-jobs/jobs/software-developer-python-90.html

In [18]:
titles = []
companies = []
locations = []
links = []

for card in python_job_cards:
    title = card.find("h2", class_="title")
    company = card.find("h3", class_="company")
    location = card.find("p", class_="location")
    url = job_card.find_all("a")[1]["href"]
    
    titles.append(title.text.strip() if title else None)
    companies.append(company.text.strip() if company else None)
    locations.append(location.text.strip() if location else None)
    links.append(url if location else None)

df = pd.DataFrame({
    'Title': titles,
    'Company': companies,
    'Location': locations,
    'Link': links
})

df

,Title,Company,Location,Link
0,Senior Python Developer,"Payne, Roberts and Davis","Stewartbury, AA",https://realpython.github.io/fake-jobs/jobs/so...
1,Software Engineer (Python),Garcia PLC,"Ericberg, AE",https://realpython.github.io/fake-jobs/jobs/so...
2,Python Programmer (Entry-Level),"Moss, Duncan and Allen","Port Sara, AE",https://realpython.github.io/fake-jobs/jobs/so...
3,Python Programmer (Entry-Level),Cooper and Sons,"West Victor, AE",https://realpython.github.io/fake-jobs/jobs/so...
4,Software Developer (Python),Adams-Brewer,"Brockburgh, AE",https://realpython.github.io/fake-jobs/jobs/so...
5,Python Developer,Rivera and Sons,"East Michaelfort, AA",https://realpython.github.io/fake-jobs/jobs/so...
6,"Back-End Web Developer (Python, Django)",Stewart-Alexander,"South Kimberly, AA",https://realpython.github.io/fake-jobs/jobs/so...
7,"Back-End Web Developer (Python, Django)","Jackson, Ali and Mckee","New Elizabethside, AA",https://realpython.github.io/fake-jobs/jobs/so...
8,Python Programmer (Entry-Level),Mathews Inc,"Robertborough, AP",https://realpython.github.io/fake-jobs/jobs/so...
9,Software Developer (Python),Moreno-Rodriguez,"Martinezburgh, AE",https://realpython.github.io/fake-jobs/jobs/so...